version: 2
updates:
  - package-ecosystem: "npm" 
    directory: "/" 
    schedule:
      interval: "weekly" 
    rebase-strategy: "auto"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "auto-update"
    # Ignore certain dependencies or major version updates
    ignore:
      - dependency-name: "next"
        update-types: ["version-update:semver-major"]
